package com.example.studiawdaniiapp.domain.models

enum class EducationType {
    ADULT_REMEDIAL_EDUCATION,
    ASSOCIATES_OR_EQUIVALENT,
    BACHELORS_OR_EQUIVALENT,
    DEGREE_TYPE_UNSPECIFIED,
    DOCTORAL_OR_EQUIVALENT,
    LOWER_SECONDARY_EDUCATION,
    MASTERS_OR_EQUIVALENT,
    PRIMARY_EDUCATION,
    UNRECOGNIZED,
    UPPER_SECONDARY_EDUCATION
}